<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
    <OutputType>Exe</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <AssemblyName>Isidore.RegressionTests</AssemblyName>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <StartupObject>RegressionTests</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="Microsoft.CSharp" />
    <Compile Include="*Regression.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="MatlabTestDouble.cs" />
    <Compile Include="..\Isidore.Matlab\MatLab.cs"><Link>MatLab.cs</Link></Compile>
    <Compile Include="..\Isidore.Matlab\Net.cs"><Link>Net.cs</Link></Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Isidore.Maths\Isidore.Maths.csproj"><Name>Isidore.Maths</Name></ProjectReference>
    <ProjectReference Include="..\Isidore.Render\Isidore.Render.csproj"><Name>Isidore.Render</Name></ProjectReference>
    <ProjectReference Include="..\Isidore.Load\Isidore.Load.csproj"><Name>Isidore.Load</Name></ProjectReference>
    <ProjectReference Include="..\Isidore.Models\Isidore.Models.csproj"><Name>Isidore.Models</Name></ProjectReference>
    <ProjectReference Include="..\Isidore.ImgProcess\Isidore.ImgProcess.csproj"><Name>Isidore.ImgProcess</Name></ProjectReference>
    <ProjectReference Include="..\Isidore.Library\Isidore.Library.csproj"><Name>Isidore.Library</Name></ProjectReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
